### ISSUE TITLE
finetuneNet.py 

### ISSUE THREAD

**Issue by sugarcane29** [yashsmehta/personality-prediction#1]
Hi...I am unable to find the file "finetuneNet.py".

Could you please tell me where it is.

Thanks.

**Comment by saminfatehi** [comment]
Hi. After storing the embeddings in a pickle file (by running LM_extractor.py), you can use files in the "finetune_models" folder (as finetuneNet), for example, "MLP_LM.py".

**Comment by sugarcane29** [comment]
okay. Thanks for the clarification.
There are some inconsistencies with the .py files in the finetune_models folder. 
Some look for the .pkl file in the root folder, while some in the same folder. 
Case in point:
LR.py Line 36 file = open('../' + inp_dir + dataset_type + '-' + embed + '-' + embed_mode + '-' + mode + '.pkl', 'rb')
MLP_LM.py Line 46 file = open(inp_dir + dataset + '-' + embed + '-' + embed_mode + '-' + mode + '.pkl', 'rb')

Would be great if you could look into them.

Thanks.
