### ISSUE TITLE
where the essays dataset came from

### ISSUE THREAD

**Issue by MiaZF** [yashsmehta/personality-prediction#12]
Hi~ 
Thanks for your sharing, which helped me a lot.

As stated in your paper "In psychometric personality trait assessments, personality is measured in continuous scores, yet the available benchmark datasets mostly provide personality traits scores in artificially binned form only. Future studies should aim to use datasets that provide continuous scores on personality traits". 

I followed the quote in your paper to read another paper named Linguistic styles: Language use as an individual difference. However, the original data is not provided in that paper. According to the description of the paper, personality is supposed to be measured in continuous scores, yet the personality is only measured by yes or no in essays. I was wondering where the essays dataset came from and whether continuous scores are used to measure personality in the original dataset.

Thank you so much!!! Looking forward to your reply !!

**Comment by yashsmehta** [comment]
Glad to hear that the code was of use, and apologies for our delay response to your questions. The essays dataset was downloaded from mypersonality.org: https://sites.google.com/michalkosinski.com/mypersonality. However, they have now decided to stop sharing the dataset with scholars. The way to obtaining the dataset would be to get in touch with the original authors, i.e. Pennebaker and King [1999]

**Comment by MiaZF** [comment]
> 

Thank you so much.

**Comment by yashsmehta** [comment]
Closing this issue now! Please re-open if its not clear.
