### ISSUE TITLE
Can't clone from repo

### ISSUE THREAD

**Issue by elhamadjidi** [yashsmehta/personality-prediction#19]
I am trying to clone from repo using google colab but it shows this error:
`Cloning into 'personality'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by huyue2022** [comment]
Have you solved this problem yet? i have also had the same problem

**Comment by harris-mohamed** [comment]
Very late reply but it is because they linked to their private Gitlab, which needs SSH authentication. Instead, use the url of the Github repo:
`git clone https://github.com/yashsmehta/personality-prediction.git`

**Comment by yashsmehta** [comment]
Sorry, we've updated this now! Thanks @harris-mohamed
