### ISSUE TITLE
Errors when running LM_extractor.py

### ISSUE THREAD

**Issue by Arkhemis** [yashsmehta/personality-prediction#4]
Hi,

I encountered some errors when running the LM_extractor.py. The first one is the following: 
```
Traceback (most recent call last):
  File "LM_extractor.py", line 111, in <module>
    map_dataset = MyMapDataset(dataset, tokenizer, token_length, DEVICE, mode)
  File "C:\Users\alexa\Desktop\code\personality-prediction-master\utils\data_utils.py", line 25, in __init__
    author_ids = torch.from_numpy(np.array(author_ids)).long().to(DEVICE)
UnboundLocalError: local variable 'author_ids' referenced before assignment
```
I think I fixed it by defining input_ids, targets,  author_ids = [] in data_utils.py. However, after this error, I had a second one:
```
Traceback (most recent call last):
  File "LM_extractor.py", line 115, in <module>
    shuffle=False,
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\dataloader.py", line 272, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\utils\data\sampler.py", line 217, in __init__
    "but got batch_size={}".format(batch_size))
ValueError: batch_size should be a positive integer value, but got batch_size=32
```
I quite don't know why is this happening, since 32 is indeed an integer? Could you help me to solve this issue?

**EDIT**: So I fixed it as well, setting batch_size=batch_size to batch_size=int(batch_size) in LM_Extactor.py apparently solve the issue.
Yet I have another issue, that is no pickle file is created. The only output of LM_Extactor when running `python LM_extractor.py -dataset_type 'essays' -token_length 512 -datafile 'data/essays/essays.csv' -batch_size 32 -embed 'bert-base' -op_dir 'pkl_data'` is 

```
usage: LM_extractor.py [-h] [-dataset_type DATASET_TYPE]
                       [-token_length TOKEN_LENGTH] [-batch_size BATCH_SIZE]
                       [-embed EMBED] [-op_dir OP_DIR] [-mode MODE]
                       [-embed_mode EMBED_MODE]
LM_extractor.py: error: unrecognized arguments: -datafile data/essays/essays.csv
```

Strange, since I followed the advice suggested in another [issue ](https://github.com/yashsmehta/personality-prediction/issues/2), and it would not work either. Looking into LM_Extactor.py, it appears that the parameter for datafile has been deleted.

Note that running `python LM_extractor.py -dataset_type 'essays' -token_length 512  -batch_size 32 -embed 'bert-base' -op_dir 'pkl_data'` without the datafile parameter indeed create a .pkl file, however at the wrong place (in the root folder, and not in the supposedly targeted folder), which is only 1Ko (so I think something's wrong here).

**EDIT2**: Okay, I found a solution. The inputs paths needed to be fixed, which is something @bateman has done in his [fork](https://github.com/bateman/personality-prediction/blob/master/utils/data_utils.py). Remains the issue of pickle files not being created at the right place.

**Comment by saminfatehi** [comment]
Hi @Arkhemis,

It was necessary to have a pkl_data directory. I modified LM_extractore.py to make this directory automatically. Now you should just pull and run the code again.
